### ISSUE TITLE
Small misunderstanding about `syne-tune/benchmarking/training_scripts/resnet_cifar10/resnet_cifar10.py`

### ISSUE THREAD

**Issue by ChongqiQu** [syne-tune/syne-tune#875]
Thank you very much for developing syne-tune.I have beening using `benchmarking` recently and found it very useful. But I found a small error or misunderstanding,as follow: 

https://github.com/syne-tune/syne-tune/blob/c535055627829c6b80b7442861963f8b413bb22e/benchmarking/training_scripts/resnet_cifar10/resnet_cifar10.py#L121

`valid_accuracy = correct / n_valid` or  `valid_error = 1- correct / n_valid`, not `valid_error = correct / n_valid` in the code

**Comment by aaronkl** [comment]
Thanks for the catch! should be addressed in #876
