### ISSUE TITLE
Is it possible for synchronization algorithms to use blackbox repository

### ISSUE THREAD

**Issue by quchongqi** [syne-tune/syne-tune#895]
Hi,boys! There is such a description in the file (```syne_tune/blackbox_repository/README.md```)：
```
This folder contains utilities to store and retrieve tabular evaluations into callable object. Any stored blackbox can be combined with surrogates which allows to interpolate between configurations that were recorded, in addition blackbox can be used to simulate asynchronous HPO experiments with Syne Tune.
```
Does this mean that the synchronization algorithm cannot use blackbox repository and blackend? If it can be used, how to use it?

**Comment by quchongqi** [comment]
OK, I understand. The synchronous algorithm uses ```blackbox repository ``` in the same way as the asynchronous algorithm. Sorry to bother you.

**Comment by aaronkl** [comment]
Thanks for reaching out! Yes blackbox repository should work with both asynchronous and synchronous scheduling
